#!/bin/sh

DIR="$( cd "$( dirname "$0"  )" && pwd  )"

ln -sf $DIR/bashrc.user ~/.bashrc.$USER
ln -sf $DIR/bashrc.alias ~/.bashrc.alias

hasSource=`cat ~/.bashrc | grep "source ~/.bashrc.$USER"`
[ ! -n "$hasSource" ] && echo "source ~/.bashrc.$USER" >> ~/.bashrc
